miltontours/models.py
from . import db

class City(db.Model):
    __tablename__ = 'cities'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'defaultcity.jpg')
    # Delete orphans so that if the City is deleted, the Tours go too
    tours = db.relationship('Tour', backref='city', cascade="all, delete-orphan")

    def __repr__(self):
        return f"ID: {self.id}\nName: {self.name}\nDescription: {self.description}"

orderdetails = db.Table('orderdetails', 
    db.Column('id', db.Integer, primary_key=True),
    db.Column('order_id', db.Integer, db.ForeignKey('orders.id'), nullable=False),
    db.Column('tour_id', db.Integer, db.ForeignKey('tours.id'), nullable=False),
    db.Column('qty', db.Integer)
)

class Tour(db.Model):
    __tablename__ = 'tours'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64),nullable=False)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False)
    price = db.Column(db.Float, nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    city_id = db.Column(db.Integer, db.ForeignKey('cities.id'))
    orders = db.relationship("Order", secondary=orderdetails, back_populates='tours')
    
    def __repr__(self):
        return f"ID: {self.id}\nName: {self.name}\nDescription: {self.description}\nPrice: ${self.price}\nCity: {self.city_id}\nDate: {self.date}"

class Order(db.Model):
    __tablename__ = 'orders'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    first_name = db.Column(db.String(64))
    surname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    total_cost = db.Column(db.Float)
    date = db.Column(db.DateTime)
    # tours = db.relationship("Tour", secondary=orderdetails, backref="orders")
    tours = db.relationship("Tour", secondary=orderdetails, back_populates='orders')
    
    def __repr__(self):
        return f"ID: {self.id}\nStatus: {self.status}\nFirst Name: {self.first_name}\nSurname: {self.surname}\nEmail: {self.email}\nPhone: {self.phone}\nDate: {self.date}\nTours: {self.tours}\nTotal Cost: ${self.total_cost}"

miltontours/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired, email

# form used in basket
class CheckoutForm(FlaskForm):
    firstname = StringField("Your first name", validators=[InputRequired()])
    surname = StringField("Your surname", validators=[InputRequired()])
    email = StringField("Your email", validators=[InputRequired(), email()])
    phone = StringField("Your phone number", validators=[InputRequired()])
    submit = SubmitField("Send to Agent")

miltontours/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap4
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.debug = True
    
    app.secret_key = 'BetterSecretNeeded123'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///milton.sqlite'
    db.init_app(app)
    
    Bootstrap4(app)
    
    from . import views
    app.register_blueprint(views.main_bp)
    from . import admin
    app.register_blueprint(admin.admin_bp)
    
    @app.errorhandler(404) 
    def not_found(e): 
      return render_template("error.html", error=e)
    @app.errorhandler(500)
    def internal_error(e):
      return render_template("error.html", error=e)
   
    return app

miltontours/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect, abort
from .models import City, Tour, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db

main_bp = Blueprint('main', __name__)

# Home page
@main_bp.route('/')
def index():
    cities = db.session.scalars(db.select(City).order_by(City.id))
    return render_template('index.html', cities=cities)

# View all the tours of a city
@main_bp.route('/tours/<int:city_id>')
def citytours(city_id):
    tours = db.session.scalars(db.select(Tour).where(Tour.city_id==city_id))
    return render_template('citytours.html', tours=tours)

# Referred to as "Basket" to the user
@main_bp.route('/order', methods=['GET', 'POST'])
def order():
    tour_id = request.values.get('tour_id')
    print(f'Values: {tour_id}')
    # Retrieve order if there is one
    if 'order_id' in session.keys():
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        # Order will be None if order_id/session is stale
    else:
        # There is no order
        order = None

    # Create new order if needed
    if order is None:
        order = Order(status=False, first_name='', surname='', email='', phone='', total_cost=0.00, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('Failed trying to create a new order!')
            order = None
    
    # Calculate total price
    total_price = 0
    if order is not None:
        for tour in order.tours:
            total_price += tour.price
    
    # Are we adding an item?
    if tour_id is not None and order is not None:
        tour = db.session.scalar(db.select(Tour).where(Tour.id==tour_id))
        try:
            order.tours.append(tour)
            for tour in order.tours:
                total_price += tour.price
            order.total_cost = total_price
            db.session.commit()
        except:
            flash('There was an issue adding the item to your basket', category='danger')
        return redirect(url_for('main.order'))
    return render_template('order.html', order=order, total_price=total_price)

@main_bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    print(f'Tour to delete ID is: {id}')
    if 'order_id' in session:
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        if not order:
            flash("There's no order to delete!")
            return redirect(request.referrer)
        print(order.tours)
        tour_to_delete = db.session.scalar(db.select(Tour).where(Tour.id==id))
        print(f'Deleting: {tour_to_delete.name}')
        try:
            tour_to_delete.qty = 0
            order.tours.remove(tour_to_delete)
            db.session.commit()
        except:
            print('Something went wrong when trying to delete the order')
            abort(500)
    return redirect(url_for('main.order'))

# Empty basket
@main_bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        order_id = session['order_id']
        try:
            order = db.session.query(Order).get(order_id)
            if order:
                db.session.delete(order)
                db.session.commit()
                session.pop('order_id')
                flash('Basket emptied!')
            else:
                flash("There's no order to delete!")
        except Exception as e:
            flash(f"An error occurred while deleting the order: {str(e)}")
    else:
        flash("There's no order to delete!")
    return redirect(url_for('main.index'))

# Complete the order
@main_bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        if not order.tours:
            flash('You need to add some tours to your basket first!')
            return(redirect(request.referrer))
        if form.validate_on_submit():
            order.status = True
            order.first_name = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            total_cost = 0
            for tour in order.tours:
                total_cost += (tour.price * tour.qty)
            order.total_cost = total_cost
            order.date = datetime.now()
            try:
                db.session.commit()
                deleteorder()
                flash('Thank you! One of our team members will contact you soon.')
                return redirect(url_for('main.index'))
            except:
                flash('There was an issue completing your order')
                return (redirect(request.referrer))
    return render_template('checkout.html', form=form)

@main_bp.route("/search", methods=['GET','POST'])
def search():
    search_query = f'%{request.args.get('search')}%'
    tours = db.session.scalars(db.select(Tour).where(Tour.description.like(search_query)))
    return render_template('citytours.html', tours=tours)

miltontours/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Milton Tours</title>
  <meta name="description" content="Milton Tours">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <style>
    /* to place border around items in the shopping basket - orders.html */
    .my-row {
      border: 1px solid grey;
    }
  </style>
</head>

<body>
  <header>

    <!-- Navbar creates a navigation bar -->
    <!-- Colours https://getbootstrap.com/docs/4.6/utilities/colors/ -->

    <nav class="navbar navbar-expand-lg navbar-light bg-info">

      <a class="navbar-brand text-light" href="{{url_for('main.index')}}">
        <img src="{{url_for('static', filename='img/miltonlogo.png')}}" width="30" height="30"
          class="d-inline-block align-top" alt="Milton Tours Logo">Milton Tours</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <a class="nav-item nav-link text-light active" href="#">About Us</a>
        <a class="nav-item nav-link text-light" href="{{url_for('main.index', _anchor='cities_anchor')}}">Cities</a>
        <a class="nav-item nav-link text-light" href="{{url_for('main.order')}}">Basket</a>
        <a class="nav-item nav-link text-light" href="discounts.html">Offers</a>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item active">
            <span class="navbar-text text-light">1-800-MILTON</span>
          </li>
          <li class="nav-item">
            <form class="form-inline my-2 my-lg-0 ml-5" action="{{url_for('main.search')}}">
              <input class="form-control" name="search" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-black btn btn-secondary btn-s my-0 ml-1" type="submit">Search</button>
            </form>
          </li>
        </ul>
    </nav>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-primary m-2" role="alert">
      {% for message in messages %}
      {{message}}
      {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    {% block head %}

    {% endblock %}

  </header>


  <!-- main page content goes in container -->
  <div class="container-fluid">
    <main>
      {% block main %}

      {% endblock %}
    </main>
  </div>

  <!-- Footer -->
  <footer class="footer">
    <div class="container text-center">
      <p>Copyright &copy; Milton Tours wyyy</p>
    </div>
  </footer>
  <!-- Footer -->


  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
    crossorigin="anonymous"></script>

</body>

</html>

miltontours/templates/checkout.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block main %}
<section>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>Checkout</h1>
        <p>
          Thank you for your interest. Please provide your details so that one of our awesome tour agents can contact
          you to finalise details and take payment. Thank you!
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        {{render_form(form)}}
      </div>
    </div>
  </div>
</section>
{% endblock %}

miltontours/templates/citytours.html
{% extends 'base.html' %}

{% block main %}
<!-- display tours for the specific city -->
<section>
  <div class="text-dark text-center">
    <div>
      <p class="h3 text-dark mb-4">Select a tour from below</p>
    </div>
  </div>
  <div class="card-columns">
    <!-- use Bootstrap card -->
    {% for tour in tours %}
    <div class="card">
      <img class="card-img-top" src="{{url_for('static', filename='img/' + tour.image)}}" alt="Card image">
      <div class="card-body">
        <h4 class="card-title">{{tour.name}}</h4>
        <p class="card-text">{{tour.description}}</p>
      </div>
      <div class="card-footer">
        <form action="{{url_for('main.order')}}">
          <input type="hidden" id="tour_id" name="tour_id" value="{{tour.id}}">
          <input class="btn btn-primary" type="submit" value="Add to Basket">
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

miltontours/templates/error.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
  <h1>Error</h1>
  <p>Sorry, but something went wrong!</p>
  <p>More info: {{error}}</p>
</div>
{% endblock %}

miltontours/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!-- add a big banner to welcome user -->
<div class="jumbotron jumbotron-fluid card card-image"
  style="background-image: url({{url_for('static', filename='img/header.jpg')}});">
  <div class="text-white text-center py-5 px-4">
    <div>
      <h1 class="display-2">Welcome to Milton Tours</h1>
      <p class="display-4 text-dark">You need a vacation!</p>
    </div>
  </div>
</div>
{% endblock %}

{% block main %}
<!-- marketing information -->
<section>
  <div class="container">
    <div class="text-white text-center">
      <div>
        <p class="h1 text-dark mb-4">Why us?</p>
      </div>
    </div>
    <!-- CSS Grid -->
    <div class="row">
      <div class="col-md-6">
        <article>
          <h2>Beautiful locations</h2>
          <p>We have tours in some of the best locations all around Australia:</p>
          <ul>
            <li>Close to city center</li>
            <li>Free shuttle service to Airport</li>
            <li>Helpful staff</li>
          </ul>
        </article>

      </div>
      <div class="col-md-6">
        <article>
          <h2>Affordable selections</h2>
          <p>We have <span> great prices and offers </span> all year round!</p>
          <p>Click <a href="discounts.html">here</a> for more information.</p>
        </article>
      </div>
    </div>
    <!-- Horizontal Rule -->
    <hr>
  </div>
</section>

<!-- display the cities to the user -->
<section>
  <div class="text-dark text-center">
    <div>
      <p class="h3 text-dark mb-4" id="cities_anchor">Pick a city to see what we have to offer!</p>
    </div>
  </div>
  <div class="card-deck">
    {% for city in cities %}
    <div class="card">
      <img class="card-img-top" src="{{url_for('static', filename='img/'+city.image)}}" alt="Card image">
      <div class="card-body">
        <h4 class="card-title">{{city.name}}</h4>
        <p class="card-text">{{city.description}}</p>
      </div>
      <div class="card-footer"><a href="{{url_for('main.citytours', city_id=city.id)}}"
          class="btn btn-primary">Tours</a></div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

miltontours/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>
  <div class="container">
    <div class="row co-12 d-flex mt-2 mb-2">
      <h3>Shopping Basket</h3>
    </div>

    <!-- each tour on seperate row -->
    {% for tour in order.tours %}
    <div class="row shadow-md my-row mb-3">
      <div class="col-sm-10 card">
        <h5 class="card-header">{{tour.date.strftime("%d/%m/%Y")}}: {{tour.city.name}} {{tour.name}}</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-2">
              <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + tour.image))}}">
            </div>
            <div class="col-10">
              <!-- Item Description -->
              <p class="card-text">{{tour.description}}</p>
            </div>
          </div>
        </div>
      </div>
      <br><br>
      <!-- right column has price and delete button -->
      <div class="col-sm-2">
        <!-- delete item button -->
        <h5 class="mt-2">{{"$%.2f"|format(tour.price)}} pp</h5>
        <p>Quantity: {{tour.qty}}</p>
        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
          <input type="hidden" id="id" name="id" value="{{tour.id}}">
          <input type="submit" value="Delete" class="btn btn-primary mb-3">
        </form>
      </div>
    </div>
    {% endfor %}

    <!-- total price and page controls -->
    <section>
      <div class="row col-12 d-flex">
        <h5 class="mt-4">Quote = {{"$%.2f"|format(total_price)}}</h5>
      </div>
      <div class="row col-12 d-flex mt-2 mb-4">
        <a href="{{url_for('main.index', _anchor='cities_anchor')}}" class="btn btn-primary mr-4">Cities</a>
        <a href="{{url_for('main.checkout')}}" class="btn btn-primary mr-4">Checkout</a>
        <a href="{{url_for('main.deleteorder')}}" class="btn btn-primary">Empty Basket</a>
      </div>
    </section>
  </div>
</section>

{% endblock %}